In [1]:
%load_ext autoreload
%autoreload 2

In [14]:
from glob import glob

from tqdm.notebook import tqdm

import atlas
from config import paths

In [3]:
cdr_forcing = "DOR"
vintage = "001"
phase = "deploy"
clobber = False

calc = atlas.global_irf_map(cdr_forcing, vintage)

In [4]:
calc = atlas.global_irf_map(cdr_forcing, vintage)

In [5]:
%%time
df = calc.df_case_status
df

CPU times: user 1.68 s, sys: 1.67 s, total: 3.35 s
Wall time: 3min 21s

,build,submitted,run_completed,archive,error,error_count,timestamp_run,JobId,JobState,Queued,yr_per_day,pe-hr_per_yr
case,,,,,,,,,,,,
smyle.cdr-atlas-v0.control.001,True,True,True,True,False,0,2024-11-04 23:44:49,None,None,False,45.61,471.47
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-01-01_00000.001,True,True,True,True,False,0,2024-11-05 03:13:08,None,None,False,58.82,365.62
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-04-01_00001.001,True,True,True,True,False,0,2024-11-05 03:12:00,None,None,False,59.00,364.49
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-07-01_00002.001,True,True,True,True,False,0,2024-11-04 20:27:38,None,None,False,58.89,365.17
smyle.cdr-atlas-v0.glb-dor_North_Atlantic_basin_000_1999-10-01_00003.001,True,True,True,True,False,0,2024-11-04 21:37:34,None,None,False,58.94,364.83
...,...,...,...,...,...,...,...,...,...,...,...,...
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_038_1999-10-01_02755.001,True,True,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-01-01_02756.001,True,True,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-04-01_02757.001,True,True,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-07-01_02758.001,True,True,False,False,False,0,NaT,None,None,False,NaN,NaN
smyle.cdr-atlas-v0.glb-dor_Southern_Ocean_039_1999-10-01_02759.001,True,True,False,False,False,0,NaT,None,None,False,NaN,NaN

In [7]:
caselist = df.loc[~df.archive].index.to_list()
len(caselist)

1346

In [12]:
archive_root = f"{paths['data']}/archive"

for case in df.loc[df.archive].index:
   # get case data files
    files = sorted(
        glob(
            f"{archive_root}/{case}/ocn/hist/{case}.pop.h.[0-9][0-9][0-9][0-9]-[0-9][0-9].nc"
        )
    )
    if not files:
        if case not in caselist:
            caselist.append(case)

len(caselist)

1346

In [15]:
for case in tqdm(caselist):
    calc.clobber_case(case)

  0%|          | 0/1346 [00:00<?, ?it/s]